spring:
  cloud:
    discovery:
      enabled: false
    config:
      allow-override: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat
  mongodb:
    embedded:
      version: latest